version: "3.8"

services:
  db:
    image: mysql:5.7
    platform: linux/amd64 # Apple Silicon でも 5.7 を動かすため
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
    ports:
      - "3367:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    volumes:
      - .:/myapp
    ports:
      - "3115:3000"
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - BOOTSNAP_DISABLE=true
      - RAILS_LOG_TO_STDOUT=true
    networks:
      - task_network

volumes:
  mysql_data:

networks:
  task_network:
    driver: bridge
